/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bind_Bind */

#ifndef _Included_com_bind_Bind
#define _Included_com_bind_Bind
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bind_Bind
 * Method:    c_coreStart
 * Signature: (Lcom/bean/Config;)Lcom/bean/Result;
 */
JNIEXPORT jobject JNICALL Java_com_bind_Bind_c_1coreStart
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
